## Put comments here that give an overall description of what your
## functions do

## sets the value of the matrix, gets the value of the matrix,
## sets the value of the inverse, gets the value of the inverse.

makeCacheMatrix <- function(x = matrix()) {
        #initialize 'm'
        m <- NULL
        #reset any previously stored inverse of this matrix
        set <- function(y){
                #input is set to x of the parent environment
                x <<- y
                #assign NULL to the m of the parent environment
                m <<- NULL
        }
        #retrieve the value of x from parent environment
        get <- function () x
        #assign to m the inverse of matrix x
        setinverse <- function(solve) m <<- solve
        #retrieve m
        getinverse <- function() m
        #create list of elements
        list(set = set, get = get,
             setinverse = setinverse, getinverse = getinverse)
}


## computes the inverse of the "matrix" returned by makeCacheMatric.
##if inverse has already been calculated, retrieves inverse from cache.

cacheSolve <- function(x, ...) {
        #sets m to be the value $getinverse in the list generated by makeCacheMatrix
        m <- x$getinverse()
        #checks if such a value has been cached; if so, returns m
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        #else, solves matrix inverse
        m <- solve(data, ...)
        x$setinverse(m)
        m
}
